site_name: estala.com
site_url: https://estalav.github.io
theme:
  language: en
  name: mkdocs
  highlights: true
  palette:
      scheme: default
      primary: amber
      accent: deep orange
nav:
    - Home: index.md
    - Projects: projects.md
markdown_extensions:
  - attr_list
  - md_in_html
