site_name: jaime.estala.com
site_url: https://estalav.github.io
theme:
  language: en
  name: mkdocs
  highlights: true
  palette:
      scheme: default
      primary: amber
      accent: deep orange
nav:
    - Curriculo: index.md
    - Projectos: projectos.md
    - logros: logros.md
    - Contactame: contactame.md

extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - attr_list
  - md_in_html
