site_name: estala.com
site_url: https://estalav.github.io
theme:
  language: en
  name: readthedocs
  highlights: true
  palette:
      scheme: default
      primary: amber
      accent: deep orange
  features:
    - content.tabs.link
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - navigation.sections
    - toc.integrate
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - header.autohide
    - content.tabs.link
    - navigation.tabs.sticky
nav:
    - Curriculo: index.md
    - Projectos: projectos.md
    - logros: logros.md
    - Contactame: contactame.md

extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - admonition
  - def_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
